/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.ClientResponse;
import com.sun.jersey.api.client.WebResource;
import com.thoughtworks.xstream.XStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JPanel;


/**
 *
 * @author teodo
 */
public class UserInterface extends javax.swing.JFrame {

    int xx;
    int xy;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");


    public UserInterface() {
        initComponents();
        charCodeBoxT.setVisible(false);
        dateLabel.setVisible(false);
        jButton1.setVisible(false);
        valueLabel.setVisible(false);
        valueLabel.setText("");
        // jPanel3.hide();
    }

    public void switchPanels(JPanel panel) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();

    }

    public List<Valute> getRates(String date) {
        List<Valute> rates = new ArrayList<>();
        XStream xstream = new XStream();
        xstream.processAnnotations(ValCurs.class);
        xstream.processAnnotations(Valute.class);
        try {

            Client client = Client.create();

            WebResource webResource = client
                    .resource("https://www.bnm.md/en/official_exchange_rates?get_xml=1&date=" + date);

            ClientResponse response = webResource.accept("application/xml")
                    .get(ClientResponse.class);

            if (response.getStatus() != 200) {
                throw new RuntimeException("Failed : HTTP error code : "
                        + response.getStatus());
            }

            String output = response.getEntity(String.class);
            ValCurs valCurs = (ValCurs) xstream.fromXML(output);

            for (Valute currentVal : valCurs.getValutes()) {
                rates.add(currentVal);
//               System.out.println(rates);
            }
        } catch (Exception e) {

            e.printStackTrace();

        }
        return rates;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        convertToPanel = new javax.swing.JPanel();
        charCodeBoxHave = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hTextField = new javax.swing.JTextField();
        wTextField = new javax.swing.JTextField();
        ConvertToButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        historyOfRatesPanel = new javax.swing.JPanel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel9 = new javax.swing.JLabel();
        ConvertHORButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        charCodeHOR = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        todayPanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        charCodeBoxT = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();

        jTextField2.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 155, 180));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(36, 39, 70));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jButton4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 155, 180));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buttons/ConvertToDefault.png"))); // NOI18N
        jButton4.setText("Convert To");
        jButton4.setToolTipText("");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ConvertToHover.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 155, 180));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buttons/TodayDefault.png"))); // NOI18N
        jButton5.setText(" Today");
        jButton5.setToolTipText("");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/TodayHover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 155, 180));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Buttons/CalendarDefault.png"))); // NOI18N
        jButton6.setText("   History of  Rates");
        jButton6.setToolTipText("");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CalendarHover.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 203, -1));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        convertToPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Currency I Have");

        jLabel3.setText("Currency I Want");

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/theo/Documents/Java Apps/CursValutar/src/main/resources/images/Convert64.png")); // NOI18N

        jLabel6.setText("Amount:");

        jLabel7.setText("Amount:");

        hTextField.setToolTipText("");
        hTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hTextFieldActionPerformed(evt);
            }
        });

        wTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wTextFieldActionPerformed(evt);
            }
        });

        ConvertToButton.setBackground(new java.awt.Color(255, 255, 255));
        ConvertToButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sendDefault.png"))); // NOI18N
        ConvertToButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sendBlack.png"))); // NOI18N
        ConvertToButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertToButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("MDL");

        javax.swing.GroupLayout convertToPanelLayout = new javax.swing.GroupLayout(convertToPanel);
        convertToPanel.setLayout(convertToPanelLayout);
        convertToPanelLayout.setHorizontalGroup(
            convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convertToPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(convertToPanelLayout.createSequentialGroup()
                        .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(charCodeBoxHave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(convertToPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, convertToPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConvertToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(wTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        convertToPanelLayout.setVerticalGroup(
            convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(convertToPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(convertToPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(convertToPanelLayout.createSequentialGroup()
                        .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(convertToPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(charCodeBoxHave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(convertToPanelLayout.createSequentialGroup()
                                .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(convertToPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ConvertToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jLayeredPane1.add(convertToPanel, "card3");

        historyOfRatesPanel.setBackground(new java.awt.Color(255, 255, 255));

        datePicker1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datePicker1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datePicker1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datePicker1MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Select Date:");

        ConvertHORButton.setBackground(new java.awt.Color(255, 255, 255));
        ConvertHORButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sendDefault.png"))); // NOI18N
        ConvertHORButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sendBlack.png"))); // NOI18N
        ConvertHORButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertHORButtonActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/theo/Documents/Java Apps/CursValutar/src/main/resources/images/HistoryOfRatesLogo128.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Select currency:");

        charCodeHOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                charCodeHORMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                charCodeHORMouseExited(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        javax.swing.GroupLayout historyOfRatesPanelLayout = new javax.swing.GroupLayout(historyOfRatesPanel);
        historyOfRatesPanel.setLayout(historyOfRatesPanelLayout);
        historyOfRatesPanelLayout.setHorizontalGroup(
            historyOfRatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyOfRatesPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(historyOfRatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyOfRatesPanelLayout.createSequentialGroup()
                        .addGroup(historyOfRatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGap(47, 47, 47)
                        .addGroup(historyOfRatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(charCodeHOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(historyOfRatesPanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(ConvertHORButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(historyOfRatesPanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        historyOfRatesPanelLayout.setVerticalGroup(
            historyOfRatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyOfRatesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(55, 55, 55)
                .addGroup(historyOfRatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(historyOfRatesPanelLayout.createSequentialGroup()
                        .addGroup(historyOfRatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(historyOfRatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(charCodeHOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConvertHORButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jLayeredPane1.add(historyOfRatesPanel, "card4");

        todayPanel.setBackground(new java.awt.Color(255, 255, 255));

        dateLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        dateLabel.setText("Today is");

        charCodeBoxT.setBackground(new java.awt.Color(255, 255, 255));
        charCodeBoxT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        charCodeBoxT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charCodeBoxTActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sendDefault.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sendBlack.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        valueLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        valueLabel.setText("value");

        javax.swing.GroupLayout todayPanelLayout = new javax.swing.GroupLayout(todayPanel);
        todayPanel.setLayout(todayPanelLayout);
        todayPanelLayout.setHorizontalGroup(
            todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayPanelLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(charCodeBoxT, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valueLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, todayPanelLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        todayPanelLayout.setVerticalGroup(
            todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(dateLabel)
                .addGap(18, 18, 18)
                .addGroup(todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(charCodeBoxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valueLabel))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jLayeredPane1.add(todayPanel, "card2");

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 470, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
//        setOpacity((float) 0.7);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        switchPanels(convertToPanel);
        LocalDate date = LocalDate.now();
        List<Valute> rates = getRates(date.format(formatter));
        for (Valute currentVal : rates) {
            charCodeBoxHave.addItem(currentVal.getCharCode());
//            charCodeBoxWant.addItem(currentVal.getCharCode());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        LocalDate date = LocalDate.now();
        dateLabel.setText("Today is " + date.format(formatter));
        System.out.println(String.valueOf(date));
        dateLabel.setVisible(true);
        charCodeBoxT.setVisible(true);
        jButton1.setVisible(true);
        valueLabel.setVisible(true);

        switchPanels(todayPanel);

        List<Valute> rates = getRates(date.format(formatter));
        for (Valute currentVal : rates) {
            charCodeBoxT.addItem(currentVal.getCharCode());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        switchPanels(historyOfRatesPanel);
       

    }//GEN-LAST:event_jButton6ActionPerformed

    private void charCodeBoxTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charCodeBoxTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charCodeBoxTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String selectedCharCode = (String) charCodeBoxT.getSelectedItem();
        LocalDate date = LocalDate.now();
        List<Valute> rates = getRates(date.format(formatter));
        for (Valute currentVal : rates) {
            if (selectedCharCode.equals(currentVal.getCharCode())) {
                valueLabel.setText(String.valueOf(currentVal.getValue()) + " MDL");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ConvertToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertToButtonActionPerformed
        // TODO add your handling code here:
        Double haveValue = Double.parseDouble(hTextField.getText());
//        Double wantValue = Double.parseDouble(wTextField.getText());
        String haveCharCode = (String) charCodeBoxHave.getSelectedItem();
//        String wantCharCode = (String) charCodeBoxWant.getSelectedItem();
        
        Double result = 0.0;
        
        LocalDate date = LocalDate.now();
        List<Valute> rates = getRates(date.format(formatter));
        for (Valute currentVal : rates) {
            if (haveCharCode.equals(currentVal.getCharCode())){
                result = currentVal.getValue() * haveValue;
            }
        }
        wTextField.setText(String.format("%.2f",result));
//        test.setText("vasea");
    }//GEN-LAST:event_ConvertToButtonActionPerformed

    private void hTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hTextFieldActionPerformed

    private void wTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wTextFieldActionPerformed

    private void ConvertHORButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertHORButtonActionPerformed
        // TODO add your handling code here:
        LocalDate selectedValue = (LocalDate) datePicker1.getDate();
        String hCharCode = (String) charCodeHOR.getSelectedItem();
        List<Valute> rates = getRates(selectedValue.format(formatter));
        for (Valute currentVal : rates) {
            if (hCharCode.equals(currentVal.getCharCode())){
                jTextField1.setText(String.format("%.2f MDL",currentVal.getValue()));
            }
        }
//        jTextField1.setText("[po");
    }//GEN-LAST:event_ConvertHORButtonActionPerformed

    private void datePicker1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datePicker1MouseClicked
        // TODO add your handling code here:
//        LocalDate selectedValue = (LocalDate) datePicker1.getDate();
//        List<Valute> rates = getRates(selectedValue.format(formatter));
//        for (Valute currentVal : rates) {
//            charCodeHOR.addItem(currentVal.getCharCode());
//        }
    }//GEN-LAST:event_datePicker1MouseClicked

    private void datePicker1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datePicker1MouseEntered
        // TODO add your handling code here:
//        LocalDate selectedValue = (LocalDate) datePicker1.getDate();
//        List<Valute> rates = getRates(selectedValue.format(formatter));
//        for (Valute currentVal : rates) {
//            charCodeHOR.addItem(currentVal.getCharCode());
//        }
    }//GEN-LAST:event_datePicker1MouseEntered

    private void charCodeHORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_charCodeHORMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_charCodeHORMouseClicked

    private void datePicker1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datePicker1MouseExited
        // TODO add your handling code here:
//        LocalDate selectedValue = (LocalDate) datePicker1.getDate();
//        List<Valute> rates = getRates(selectedValue.format(formatter));
//        for (Valute currentVal : rates) {
//            charCodeHOR.addItem(currentVal.getCharCode());
//        }
    }//GEN-LAST:event_datePicker1MouseExited

    private void charCodeHORMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_charCodeHORMouseExited
        // TODO add your handling code here:
        LocalDate selectedValue = (LocalDate) datePicker1.getDate();
        List<Valute> rates = getRates(selectedValue.format(formatter));
        for (Valute currentVal : rates) {
            charCodeHOR.addItem(currentVal.getCharCode());
        }
    }//GEN-LAST:event_charCodeHORMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertHORButton;
    private javax.swing.JButton ConvertToButton;
    private javax.swing.JComboBox<String> charCodeBoxHave;
    private javax.swing.JComboBox<String> charCodeBoxT;
    private javax.swing.JComboBox<String> charCodeHOR;
    private javax.swing.JPanel convertToPanel;
    private javax.swing.JLabel dateLabel;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JTextField hTextField;
    private javax.swing.JPanel historyOfRatesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel todayPanel;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField wTextField;
    // End of variables declaration//GEN-END:variables
}
